package com.siva.tableinslizer;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;

// when is comment after creation table in database because every time calls but nor creation

//@Component 
public class DatabaseInitializer {

	@Autowired
	private  DatabaseClient client;
	/* private final DatabaseClient client;
	
	public DatabaseInitializer(DatabaseClient client) {
	    this.client = client;
	}*/
	public DatabaseInitializer() {
	   System.out.println("DatabaseInitializer.No-argsConstrctor");
	}

    @PostConstruct
    public void initialize() {
        client.sql("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE GAMER (
                    GAMER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    GAMER_NAME VARCHAR2(20),
                    GAMER_LOC VARCHAR2(30),
                    GAMER_PHNO NUMBER(15),
                    GENDER VARCHAR2(10),
                    GAME_TYPE VARCHAR2(20)
                )';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
            """).fetch().rowsUpdated().subscribe();
        
        System.out.println("DatabaseInitializer.initialize()- Table is created"); 
    }
}
